
package com.demo.from;

public class SetFrom {

	 private Integer wapId;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column waps.wap_url
	     *
	     * @mbggenerated
	     */
	    private String wapUrl;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column waps.wap_title
	     *
	     * @mbggenerated
	     */
	    private String wapTitle;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column waps.wap_desc
	     *
	     * @mbggenerated
	     */
	    private String wapDesc;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column waps.wap_key_word
	     *
	     * @mbggenerated
	     */
	    private String wapKeyWord;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column waps.wap_money
	     *
	     * @mbggenerated
	     */
	    private Integer wapMoney;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column waps.user_id
	     *
	     * @mbggenerated
	     */
	    private Integer userId;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column waps.is_ pop
	     *
	     * @mbggenerated
	     */
	    private Boolean isPop;

		public Integer getWapId() {
			return wapId;
		}

		public void setWapId(Integer wapId) {
			this.wapId = wapId;
		}

		public String getWapUrl() {
			return wapUrl;
		}

		public void setWapUrl(String wapUrl) {
			this.wapUrl = wapUrl;
		}

		public String getWapTitle() {
			return wapTitle;
		}

		public void setWapTitle(String wapTitle) {
			this.wapTitle = wapTitle;
		}

		public String getWapDesc() {
			return wapDesc;
		}

		public void setWapDesc(String wapDesc) {
			this.wapDesc = wapDesc;
		}

		public String getWapKeyWord() {
			return wapKeyWord;
		}

		public void setWapKeyWord(String wapKeyWord) {
			this.wapKeyWord = wapKeyWord;
		}

		public Integer getWapMoney() {
			return wapMoney;
		}

		public void setWapMoney(Integer wapMoney) {
			this.wapMoney = wapMoney;
		}

		public Integer getUserId() {
			return userId;
		}

		public void setUserId(Integer userId) {
			this.userId = userId;
		}

		public Boolean getIsPop() {
			return isPop;
		}

		public void setIsPop(Boolean isPop) {
			this.isPop = isPop;
		}
}
