package com.demo.dao;

import com.demo.model.Keys;

public interface KeysMapper extends SqlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keys
     *
     * @mbggenerated
     */
    int insert(Keys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keys
     *
     * @mbggenerated
     */
    int insertSelective(Keys record);
}