package com.demo.dao;

import com.demo.model.Waps;

import java.util.List;
import java.util.Map;

public interface WapsMapper extends SqlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waps
     *
     * @mbggenerated
     */
    int insert(Waps record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waps
     *
     * @mbggenerated
     */
    int edit(Waps record);


    int delete(int[] ids);

    int count(Map<String,Object> record);

    List<Waps> query(Map<String,Object> record);
}