package com.demo.dao;

import com.demo.model.Waps;

import java.util.List;

public interface WapsMapper extends SqlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waps
     *
     * @mbggenerated
     */
    int insert(Waps record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waps
     *
     * @mbggenerated
     */
    int insertSelective(Waps record);


    List<Waps> query(Waps record);
}