package com.demo.service;


/**
 * Created by Unitv on 2016/8/18.
 */
public interface BaseServiceImpl<T> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authen
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(int id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authen
     *
     * @mbggenerated
     */
    int insert(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authen
     *
     * @mbggenerated
     */
    int insertSelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authen
     *
     * @mbggenerated
     */
    T selectByPrimaryKey(int id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authen
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authen
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(T record);
}
