package com.demo.model;

public class Keys {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keys.key_id
     *
     * @mbggenerated
     */
    private Integer keyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keys.key_word
     *
     * @mbggenerated
     */
    private String keyWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keys.key_money
     *
     * @mbggenerated
     */
    private Integer keyMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keys.key_weight
     *
     * @mbggenerated
     */
    private Byte keyWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keys.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keys.key_id
     *
     * @return the value of keys.key_id
     *
     * @mbggenerated
     */
    public Integer getKeyId() {
        return keyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keys.key_id
     *
     * @param keyId the value for keys.key_id
     *
     * @mbggenerated
     */
    public void setKeyId(Integer keyId) {
        this.keyId = keyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keys.key_word
     *
     * @return the value of keys.key_word
     *
     * @mbggenerated
     */
    public String getKeyWord() {
        return keyWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keys.key_word
     *
     * @param keyWord the value for keys.key_word
     *
     * @mbggenerated
     */
    public void setKeyWord(String keyWord) {
        this.keyWord = keyWord == null ? null : keyWord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keys.key_money
     *
     * @return the value of keys.key_money
     *
     * @mbggenerated
     */
    public Integer getKeyMoney() {
        return keyMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keys.key_money
     *
     * @param keyMoney the value for keys.key_money
     *
     * @mbggenerated
     */
    public void setKeyMoney(Integer keyMoney) {
        this.keyMoney = keyMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keys.key_weight
     *
     * @return the value of keys.key_weight
     *
     * @mbggenerated
     */
    public Byte getKeyWeight() {
        return keyWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keys.key_weight
     *
     * @param keyWeight the value for keys.key_weight
     *
     * @mbggenerated
     */
    public void setKeyWeight(Byte keyWeight) {
        this.keyWeight = keyWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keys.user_id
     *
     * @return the value of keys.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keys.user_id
     *
     * @param userId the value for keys.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}