package com.demo.model;

public class Waps {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waps.wap_id
     *
     * @mbggenerated
     */
    private Integer wapId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waps.wap_url
     *
     * @mbggenerated
     */
    private String wapUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waps.wap_title
     *
     * @mbggenerated
     */
    private String wapTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waps.wap_desc
     *
     * @mbggenerated
     */
    private String wapDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waps.wap_key_word
     *
     * @mbggenerated
     */
    private String wapKeyWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waps.wap_money
     *
     * @mbggenerated
     */
    private Integer wapMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waps.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waps.is_ pop
     *
     * @mbggenerated
     */
    private Boolean isPop;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waps.wap_id
     *
     * @return the value of waps.wap_id
     *
     * @mbggenerated
     */
    public Integer getWapId() {
        return wapId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waps.wap_id
     *
     * @param wapId the value for waps.wap_id
     *
     * @mbggenerated
     */
    public void setWapId(Integer wapId) {
        this.wapId = wapId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waps.wap_url
     *
     * @return the value of waps.wap_url
     *
     * @mbggenerated
     */
    public String getWapUrl() {
        return wapUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waps.wap_url
     *
     * @param wapUrl the value for waps.wap_url
     *
     * @mbggenerated
     */
    public void setWapUrl(String wapUrl) {
        this.wapUrl = wapUrl == null ? null : wapUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waps.wap_title
     *
     * @return the value of waps.wap_title
     *
     * @mbggenerated
     */
    public String getWapTitle() {
        return wapTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waps.wap_title
     *
     * @param wapTitle the value for waps.wap_title
     *
     * @mbggenerated
     */
    public void setWapTitle(String wapTitle) {
        this.wapTitle = wapTitle == null ? null : wapTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waps.wap_desc
     *
     * @return the value of waps.wap_desc
     *
     * @mbggenerated
     */
    public String getWapDesc() {
        return wapDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waps.wap_desc
     *
     * @param wapDesc the value for waps.wap_desc
     *
     * @mbggenerated
     */
    public void setWapDesc(String wapDesc) {
        this.wapDesc = wapDesc == null ? null : wapDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waps.wap_key_word
     *
     * @return the value of waps.wap_key_word
     *
     * @mbggenerated
     */
    public String getWapKeyWord() {
        return wapKeyWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waps.wap_key_word
     *
     * @param wapKeyWord the value for waps.wap_key_word
     *
     * @mbggenerated
     */
    public void setWapKeyWord(String wapKeyWord) {
        this.wapKeyWord = wapKeyWord == null ? null : wapKeyWord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waps.wap_money
     *
     * @return the value of waps.wap_money
     *
     * @mbggenerated
     */
    public Integer getWapMoney() {
        return wapMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waps.wap_money
     *
     * @param wapMoney the value for waps.wap_money
     *
     * @mbggenerated
     */
    public void setWapMoney(Integer wapMoney) {
        this.wapMoney = wapMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waps.user_id
     *
     * @return the value of waps.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waps.user_id
     *
     * @param userId the value for waps.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waps.is_ pop
     *
     * @return the value of waps.is_ pop
     *
     * @mbggenerated
     */
    public Boolean getIsPop() {
        return isPop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waps.is_ pop
     *
     * @param isPop the value for waps.is_ pop
     *
     * @mbggenerated
     */
    public void setIsPop(Boolean isPop) {
        this.isPop = isPop;
    }

    public Waps() {
    }

    public Waps(String wapTitle, String wapDesc, String wapKeyWord) {

        this.wapTitle = wapTitle;
        this.wapDesc = wapDesc;
        this.wapKeyWord = wapKeyWord;
    }
}